PDMC.x : qmc.F90 pdmc.F90 utilities.F90 WFC.F90 AOs.F90 MOs.F90 drift.F90 energies.F90
	gfortran -o PDMC.x qmc.F90 pdmc.F90 utilities.F90 WFC.F90 AOs.F90 MOs.F90 drift.F90 energies.F90
clean :
	rm *.out *.png
plot :
	gnuplot plot.p	
